version: 2

.build_template: &build_definition
  steps:
    - checkout
    - run: bundle install --jobs=3 --retry=3 --path vendor/bundle
    - run:
        name: Set bundler path
        command: bundle --path vendor/bundle
    - run:
        name: Install OpenALPR
        command: apt-get update && apt-get install -y openalpr openalpr-daemon openalpr-utils libopenalpr-dev
    - run:
        name: Run tests
        command: bundle exec rake test
        when: always
    - store_test_results:
        path: test/reports
  working_directory: ~/app

jobs:
  test_ruby_2_6:
    <<: *build_definition
    docker:
      - image: ruby:2.6.3
  test_ruby_2_5:
    <<: *build_definition
    docker:
      - image: ruby:2.5.5
  test_ruby_2_4:
    <<: *build_definition
    docker:
      - image: ruby:2.4.6
  test_ruby_2_3:
    <<: *build_definition
    docker:
      - image: ruby:2.3.8

workflows:
  version: 2
  test_ruby__versions:
    jobs:
      - test_ruby_2_6
      - test_ruby_2_5
      - test_ruby_2_4
      - test_ruby_2_3
